title: David NN
description: Systemarkitekt - akademiska meriter inom systemutveckling, f√∂retagsekonomi och design
show_downloads: false
theme: jekyll-theme-minimal

plugins:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
